### ISSUE TITLE
Project file not found

### ISSUE THREAD

**Issue by bdnstn** [MtSamsonite/ha-cbus2mqtt#1]
Project file backup placed in \config\ and configured, but isn't found or used.
![image](https://user-images.githubusercontent.com/24848173/187016868-19823b71-13ad-4b20-b7f9-1b78a77df770.png)

`CMQTTD_PROJECT_FILE = /config/BURS1303.cbz`
`...`
`/config/BURS1303.cbz not found; using generated labels.`

**Comment by MtSamsonite** [comment]
@bdnstn,  My apologies, I am a novice and this is my first add-on.   When I created the add-on I did indeed map /config for access, however I subsequently realised this is wrong and users may not trust an add-on that with access to their config directory.
The correct method I learned is to use /share.   I changed this between ver .04 and 0.5 and at the time had very few downloads so whilst a breaking change I did not think it was likely to impact many if any at all.   Unfortunately you must have used the earlier version. 
So once again my apologies but if you move your file to somewhere below /share and update the config option it should find your file.
