### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [MtSamsonite/ha-cbus2mqtt#3]
Hi and thanks for the HA add-on.

I have successfully installed your add-on into my HA and connected it through to my MQTT broker.

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Importing the add-on configuration options as script variables
Completed importing addon configuration options
The following variable values were passed through via the Home Assistant add on configuration options
MQTT_USER = cbus2mqtt
MQTT_PASSWORD = NOT DISPLAYED IN LOG FILE
MQTT_SERVER = core-mosquitto
TCP_OR_SERIAL = Use a IP connection to CBUS
CBUS_CONNECTION = 192.168.15.99:10001
MQTT_USE_TLS = null
MQTT_PORT = null
CMQTTD_CA_CERT_PATH = null
CMQTTD_CLIENT_CERT_PATH = null
CMQTTD_CLIENT_KEY_PATH = null
CMQTTD_PROJECT_FILE = null
CBUS_TIMESYNC = null
CBUS_CLOCK = null
CMQTTD_LOG_LEVEL = null
Creating file /etc/cmqttd/auth
Using TCP CNI at 192.168.15.99:10001
Disabling TLS support.
Using MQTT login details in /etc/cmqttd/auth
No value was provided for CMQTTD_PROJECT_FILE; using generated labels.
 
Local time zone: Australia/Sydney
Current time: Sat, 08 Jul 2023 19:11:35 +1000
Running cmqttd with flags: --broker-address core-mosquitto --timesync 300 --tcp 192.168.15.99:10001 --broker-disable-tls --broker-auth /etc/cmqttd/auth
2023-07-08 19:11:35,866 Transport security disabled!
2023-07-08 19:11:35,994 Connected to MQTT broker`

Now what???

There are no topics or messages being published to my MQTT broker however I can see the cbus2mqtt user has connected.

Do I need to send a command to a topic to force it to read data from the Cbus or do I need to do something in the Cbus to get it to send data out? 

Thanks for the help.

**Comment by lowgoz** [comment]
head to /integrations/dashboard and you should see 254 or so CBUS lights under your MQTT integration
![image](https://github.com/MtSamsonite/ha-cbus2mqtt/assets/47404041/0b2d8bd5-13e1-447f-908a-3f677e31647f)

**Comment by bigfeetneedbigboots** [comment]
Ah, yes I do. Thank you for the assist,
